### ISSUE TITLE
Verkaufs-Status-Push

### ISSUE THREAD

**Issue by Spacelord-XaN** [braunau-mobil/velo-basar#1]

**Comment by PhilMuehlberger** [comment]
REST URL Normalfall:
http://127.0.0.1:8080/wp-json/bm/v1/velobasar/

REST URL im Fall WP ohne Permalinks:
http://127.0.0.1:8080/?rest_route=/bm/v1/velobasar/

Die URL sollte im WP Plugin Admin Panel ausgegeben werden, siehe entsprechender Issue

**Comment by PhilMuehlberger** [comment]
![rest](https://user-images.githubusercontent.com/51225217/64459433-24d64600-d0f8-11e9-85a9-b7b5ca3278a8.jpg)

**Comment by PhilMuehlberger** [comment]
Discussion: We might need to rename auth header to 'Authorization', renaming 'bm_velobasar_api_token'. Need to check. Opened separate plugin issue for this.

**Comment by PhilMuehlberger** [comment]
Hier die echte Push URL
https://www.braunaumobil.at/wp-json/bm/v1/velobasar
