### ISSUE TITLE
Check Abrechnung aller Verkäufer

### ISSUE THREAD

**Issue by hitzgingerev** [braunau-mobil/velo-basar#100]
Wie können wir sicherstellen, dass alle Verkäufer abgerechnet wurden?
Müssen hier alle IDs einzeln durchgesehen werden?

**Comment by Spacelord-XaN** [comment]
Auf der Basar Übersicht könnte man entweder ein Diagramm, oder eine einfache Zahl anzeigen.

Alternativ dazu wäre vermutlich ein Filter in der Verkäuferliste sinnvoll: "Nicht Abgerechnet"

**Comment by hitzgingerev** [comment]
Nachdem wir die Übersicht am Ende vom Basar benötigen (um zu prüfen, ob die nicht aktiv zur Abholung gekommen sind - IBAN angegeben haben), macht meiner Meinung nach nur die Verkäuferliste sind - da wir diese ja dann selbst abrechnen und überweisen

**Comment by Spacelord-XaN** [comment]
In der Verkäuferliste gibt es nun einen Filter:
* Alle
* Abgerechnet
* Nicht Abgerechnet

**Comment by hitzgingerev** [comment]
fixed
