### ISSUE TITLE
Link Artikel-Verkäufer

### ISSUE THREAD

**Issue by MarkusDutzler** [braunau-mobil/velo-basar#106]
Wie komme ich von einer bekannten Artikel-ID zum Verkäufer?

**Comment by hitzgingerev** [comment]
Ich finde es auch hilfreich, wenn in der Artikelübersichts-Liste die Verkaufs-ID als Spalte angezeigt wird - oder/und falls einfacher, dann in den Artikeldetails

**Comment by Spacelord-XaN** [comment]
In der Artikelliste wird nun die Verkäufer ID als Link angezeigt.
