### ISSUE TITLE
Fehler beim "verschwunden" markieren

### ISSUE THREAD

**Issue by MarkusDutzler** [braunau-mobil/velo-basar#107]
Wenn ich einen Artikel als verschwunden markiere kommt folgender Fehler:

Error.
An error occurred while processing your request.

Request ID: |b28d1e2b-4180faca699ba93f.

**Comment by MarkusDutzler** [comment]
Wenn ich eingelogt bin als Administrator gehts. Das sollte aber entweder jeder können oder die meldung kommen dass das nur der Admin darf.

**Comment by Spacelord-XaN** [comment]
Es können nun alle Benutzer Artikel Sperren oder als Verschwunden markieren.
Entsperren kann nur der Administrator.

**Comment by hitzgingerev** [comment]
retest 04.1.20 - funktioniert
