### ISSUE TITLE
Abrechnung stornieren

### ISSUE THREAD

**Issue by MarkusDutzler** [braunau-mobil/velo-basar#108]
Ein Abrechnungsbeleg soll komplett storniert werden können (ev. nur als Admin) um Änderungen des Status vornehmen zu können (Usecase: Artikel wird erst nach Abrechnung als verschwunden erkannt)

**Comment by Spacelord-XaN** [comment]
Soll das Storno einer Abrechnung eine eigene Transaktion sein?
Im dem Sinn dass man diesen Vorgang nachvollziehen kann.

Oder reicht es aus dass es sich hierbei um eine Art Lösch-Funktion handelt:
* Die Abrechnungstransaktion wird gelöscht (Es würde in der Nummer eine Lücke entstehen)
* Alle darin enthaltenen Artikel sowie der Verkäufer werden wieder auf NoSettled gesetzt

**Comment by Spacelord-XaN** [comment]
Die Settlement Transaktion soll gelöscht werden und alle Stati wieder korrekt zurückgesetzt werden.
