### ISSUE TITLE
Fehler Annahmebeleg drucken

### ISSUE THREAD

**Issue by hitzgingerev** [braunau-mobil/velo-basar#110]
Anlage neuer Verkäufer ok, Artikel erfassen ok, bei Annahmebeleg drucken kommt diese Fehlermeldung:

![Fehler_Annahmebeleg_drucken_04 01 20](https://user-images.githubusercontent.com/59145234/71764527-2a4a6e00-2ee9-11ea-9c99-98a13ee5f193.jpg)

**Comment by Spacelord-XaN** [comment]
fixed

**Comment by hitzgingerev** [comment]
Retest 04.01.20 - ok
