### ISSUE TITLE
LogIn / Öffnen Basar funkt nicht

### ISSUE THREAD

**Issue by hitzgingerev** [braunau-mobil/velo-basar#116]
![Fehler_Login](https://user-images.githubusercontent.com/59145234/73122621-4640ad00-3f87-11ea-8cd4-11e78fd5c40a.jpg)

**Comment by Spacelord-XaN** [comment]
Das liegt daran dass sich in der Datenbank etwas geändert hat, diese muss gelöscht werden.
Bitte versuche mal folgendes:
* Alle Programme schließen
* Tastenkombination [WIN]+[R]
* Folgenden Befehl einfügen und mit [ENTER] ausführen:
"%ProgramFiles%\PostgreSQL\12\bin\psql" -U postgres -c "DROP DATABASE velobasar
* Es sollte eine schwarze Kommandozeilenbox kommen wo du nach dem Passwort für postgres gefragt wirst.
* Das Passwort (root) eingeben und mit [ENTER] bestätigen

Danach bitte nochmal versuchen.

**Comment by hitzgingerev** [comment]
Leider geht es noch immer nicht... siehe neue Fehlermeldung

![Fehler_Login_2](https://user-images.githubusercontent.com/59145234/73125743-95e4a000-3faa-11ea-9248-ad2021f8fab3.jpg)

**Comment by Spacelord-XaN** [comment]
Könntest du die Schritte von https://github.com/braunau-mobil/velo-basar/issues/116#issuecomment-578420864 nochmal machen?

**Comment by hitzgingerev** [comment]
fixed
