### ISSUE TITLE
Initial startup DB sequence issue?

### ISSUE THREAD

**Issue by PhilMuehlberger** [braunau-mobil/velo-basar#140]
After migrating to dotnet 3.1 (Ubuntu) and postgres 10 I try to resetup my local system.
DB creation finally worked using `dotnet ef database update`. DB tables seem ok and are empty.
App startup is fine, but accessing the app brings up a sequence error as shown in image.
I already assigned value 1 to all of our 10 sequences. Still same error.
Guess I am doing it wrong, no idea.
![dbinit](https://user-images.githubusercontent.com/51225217/73455858-20dde580-4371-11ea-9e31-069b06d5ec03.jpg)

**Comment by Spacelord-XaN** [comment]
Hast du de DB vorher gedroppt?
Weils ab jetzt migrations gibt, aber man muss vorher einmalig die alte DB droppen.

**Comment by PhilMuehlberger** [comment]
Fck thats it. Danke! Ich war zu kompliziert.
Hatte DB komplett neu erstellt nach Postgres 10 update, weil 9 nicht mehr ging wegen generated Keyword. Ich hätte danach nur die App starten muessen, ohne die DB auch nur leer zu erstellen. Läuft. Hammer.
