### ISSUE TITLE
Basar Statistik

### ISSUE THREAD

**Issue by Spacelord-XaN** [braunau-mobil/velo-basar#48]
https://github.com/d3/d3/wiki/Gallery

**Comment by Spacelord-XaN** [comment]
https://www.chartjs.org/

**Comment by Spacelord-XaN** [comment]
@MarkusDutzler Was für Sachen wären denn interesant?

**Comment by MarkusDutzler** [comment]
Des is ja bunt uuuuuund in Farbe. Des überfordert mich ja fast ;)

Ich probiers jetzt mal von der anderen Seite und schaue mal welche Daten für mich in der Vergangenheit aus dem alten System interessant waren.

Immer bezogen auf den aktuellen Basar:
- "in welcher Kategorie wurde wieviel abgegeben" -> ein Tortendiagramm für Anzahl und eins für Wert, Zahlen sollten dabei stehen und auch die Gesamtzahl drunter oder so.
- "in welcher Kategorie wurde wieviel verkauft" -> gleich abgegeben oder ins abgegeben Diagramm integriert (verschiedene Farbschatierungen z.B.)
- "Anzahl aller Verkäufer:" -> Zahl (nix bunt und in Farbe :-p)
- "Wieviel ist verschwunden:" -> Zahl oder tortendiagramm nach Kategorie. Zahl ist zwar neu aber wäre wichtig zwecks da Abrechnung.
- "Preis des teuersten und des günstigsten Artikels" -> Zahl, alternativ wäre ein Kurzve mit Anzahl der artikel auf der y-Achse und 10€ schritte auf der x-Achse cool. Also ein balken oder linien Diagramm. Sowas auf die Art (https://github.com/liufly/Dual-scale-D3-Bar-Chart oder https://observablehq.com/@d3/line-chart) könnte man auch mit den tatsächlich verkauften kombinieren.

Mehr wollte ich jetzt nicht wissen, bzw. ist indirekt eh irgendwo anders dann drin, so wie die wichtigen Daten wieviel war da und wie viel wurde verkauft.

Ich hoff das war jetzt net komplett vorbei an dem was du wissen willst. Und zu de 2 Links, des chartjs schaut aus als obs alles kann was ma braucht und schaut einfacher aus.
