### ISSUE TITLE
Why are products not basar specific

### ISSUE THREAD

**Issue by Spacelord-XaN** [braunau-mobil/velo-basar#61]
kt

**Comment by PhilMuehlberger** [comment]
Schwierige Frage. Der Begriff Products passt hier irgendwie nicht. Sale Item wäre sicher basarspezifisch.

**Comment by MarkusDutzler** [comment]
Weil diese mit der Annahme mit dem Basar verknüpft sind?

Bzw. fiese Gegenfrage: Warum sollten sie Basarspezifisch sein?

**Comment by Spacelord-XaN** [comment]
@MarkusDutzler stimmt
