### ISSUE TITLE
The BasarId Dilemma

### ISSUE THREAD

**Issue by Spacelord-XaN** [braunau-mobil/velo-basar#62]
BasarId is passed through every single request.

Is this a good idea?

Alternatives:
* Mark the active Basar in DB
* Cookie
* ???

**Comment by PhilMuehlberger** [comment]
Maybe store in session?

**Comment by Spacelord-XaN** [comment]
What would be a session, technically?
ASP.NET Core says this about sessions:
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/app-state?view=aspnetcore-3.0

**Comment by PhilMuehlberger** [comment]
Aber wäre das nicht vielleicht ein zwingender Admin Config Parameter, ohne den es einfach nicht geht? Dann ist er nicht mehr in den Requests nötig.

**Comment by Spacelord-XaN** [comment]
Ja genau das frage ich mich auch, bzw. mein ich das obe mit "Mark the active Basar id DB".

Ich bin nämlich gerade am refactoring und diese Kack Basar Id ist mir nur im weg.

**Comment by PhilMuehlberger** [comment]
Session would be a temporary DB or in-memory context for a browser session with user login lifetime or with defined expiry. Referenced with a session id passed as parameter would it hold all kind of contextual information. This is server side. this requires session expiry, like garbage collection.

**Comment by Spacelord-XaN** [comment]
Es wäre halt dann nicht mehr so flexibel. Aktuell könnte man jederzeit den Basar wechseln und dort Sachen nachsehen. Aber ob das jemand braucht?

**Comment by Spacelord-XaN** [comment]
@Session
Ok verstehe, dass is keine Technologie sonder eher ein Konzep. Heißt man müsste sich was überlegen und das dann implementieren.

**Comment by PhilMuehlberger** [comment]
admin parameter (default) that can be overridden with request parameter?

**Comment by Spacelord-XaN** [comment]
Das wäre natürlich am flexibelsten.

**Comment by PhilMuehlberger** [comment]
@session should be supported by framework in some way. quite old concept. maybe no longer state of the art, no idea.

**Comment by Spacelord-XaN** [comment]
Admin Paramater für alle Unauthorized User

Authorized User defaulten auf den Admin Parameter, können jedoch einen ander Basar auswählen. Der wird  in einem Cookie Persistiert.

**Comment by MarkusDutzler** [comment]
An Unauthorized User has no need to chance the basar, but the admin should have the possibility to look back to old basars without interupting the running basar. So your last comment sounds quite good to me if this is not too much work. 

Otherwise a static ID which is parameterized in admin zone and stays untouched while basar is also ok, because i see no critical need to look back to old basars while a running basar.
