### ISSUE TITLE
Cart in the Cookies?

### ISSUE THREAD

**Issue by Spacelord-XaN** [braunau-mobil/velo-basar#63]
Curently the cart is stored as a list of product ids - in a cookie.

Is this good?

Alternatives:
* Table cart, where every time a new sale is created a new cartId is generated, or so?

**Comment by MarkusDutzler** [comment]
As far as i remember we decided that there is no interaction to a table until the cart is checked out. Or am i wrong in this point?

So i see ne advantage of an server interaction before the checkout. Since this a client side cookie is good.

**Comment by Spacelord-XaN** [comment]
Cookies werden ja trotzdem übertragen, aber der Warenkorb besteht ja nur aus einer Liste von Ids.
Lassen wir so.
