### ISSUE TITLE
Brauchen wir das Basar.IsLocked Flag

### ISSUE THREAD

**Issue by Spacelord-XaN** [braunau-mobil/velo-basar#64]
Aktuell gibts im Model vom Basar ein Flag: IsLocked

Ich habe das vorgesehen dass man diesen Basar sperren kann.

Nun gibt es aber in den Einstellungen ja den Aktiven Basar. Dieser gilt für alle nicht autorisierten Benutzer.

Sehe gerade keinen Sinn in diesem Flag.

Bitte um Meinungen.

**Comment by PhilMuehlberger** [comment]
Ok, einziger Sinn für mich: Sperre gegen jedweden Schreibzugriff, auch gegen Admin. Beispielsweise bei Finanzprüfung oder was. Ansonsten für uns intern überflüssig, oder?

**Comment by MarkusDutzler** [comment]
Für eine Finanzprüfung hat die software sowieso keine bedeutung, ausser als Indiz. 
Ich würde den sinn nur in einer sperre gegen versehentliche editierung sehen, das wäre aber ein feature. Allerdings kein notwendiges, ja nicht mal wirklich nice to have.
