### ISSUE TITLE
Display resolution and ratio

### ISSUE THREAD

**Issue by Spacelord-XaN** [braunau-mobil/velo-basar#67]
Bitte eine Liste machen der Bildschirmauflösungen inkl. Seitenverhältins der Verreinsnotebooks.

**Comment by MarkusDutzler** [comment]
Toshiba Satelite Pro 16:9 1600:900
HP Compaq nc6320 4:3 1024:768
HP Compaq nx7400 16:9 1280:800
Toshiba Satelite Pro 16:9 1280:800
HP Compaq nx9420 16:9 1680:1050
Acer Aspire 5920G 4:3 1024:768
