### ISSUE TITLE
Abrechungsbeleg - Verschwunden & Gesperrt

### ISSUE THREAD

**Issue by Spacelord-XaN** [braunau-mobil/velo-basar#90]
Sollen Artikel die als "Verschwunden" oder "Gesperrt" markiert wurden, auf dem Abrechnungsbeleg aufgeführt werden?

**Comment by MarkusDutzler** [comment]
Verschwunden wird abgerechnet als wäre es verkauft worden.

Gesperrte artikel werden unverkauft zurückgegeben. Diese können nur nicht mehr verkauft werden.
