### ISSUE TITLE
Prüfung Länge IBAN

### ISSUE THREAD

**Issue by hitzgingerev** [braunau-mobil/velo-basar#91]
Testbasar_Evelyn:

Maske: Verkäuferdaten erfassen
Prüfung Länge bei IBAN-Erfassung wäre sinnvoll

**Comment by Spacelord-XaN** [comment]
Macht Sinn.
https://de.wikipedia.org/wiki/Internationale_Bankkontonummer

**Comment by hitzgingerev** [comment]
Bei Eingabe eines IBANs wird das Feld immer rot, egal ob Eingabe mit Leerzeichen oder ohne

Meiner Meinung nach müssten folgende Kriterien sein?:
- für DE 22 Stellen gesamt
- für AT 20 Stellen gesamt

Was hast du hier eingestellt?

**Comment by Spacelord-XaN** [comment]
Also das  Verhalten kann ich nicht reproduzieren. Bei mir werden folgende Eingaben korrekt verarbeitet:
* Nichts ausfüllen
* Österrreichische IBAN mit Leerzeichen

Es sollten eigentlich alle IBANs akzeptiert werden, da ich die Checksummenprüfung eingebaut habe. Also es muss ich um eine gültige europäische IBAN handeln.

**Comment by hitzgingerev** [comment]
Retest 4.1.20 erfolgreich... :-)
