### ISSUE TITLE
Artikel erfassen - Preis 0,00

### ISSUE THREAD

**Issue by hitzgingerev** [braunau-mobil/velo-basar#93]
Testbasar_Evelyn

Maske: Annahme - Artikel erfassen:
Preis 0,00 sollte nicht zulässig sein, da bereits mit 0,00 vorbelegt und kann leicht übersehen/vergessen werden

**Comment by Spacelord-XaN** [comment]
Als Preis muss nun mindestens "0,01" eingegeben werden.

**Comment by hitzgingerev** [comment]
Retest 31.12.19 - ok
