### ISSUE TITLE
Maske Neue Annahme - Fehler Artikel erfassen - Verkaufs-ID Nr. 5

### ISSUE THREAD

**Issue by hitzgingerev** [braunau-mobil/velo-basar#94]
Testbasar_Evelyn:

Maske Artikel erfassen bei Verkaufs-ID Nr. 5
Bei 10 Artikel kann nicht gespeichert werden - folgende Fehlermeldung
![Artikelanlage_IDNr5_mehr als 10 Artikel](https://user-images.githubusercontent.com/59145234/71580085-84b98800-2aff-11ea-9181-ec51f5e63eb0.jpg)

**Comment by Spacelord-XaN** [comment]
fixed

**Comment by hitzgingerev** [comment]
retest 04.10.20 ok
