### ISSUE TITLE
Maske Etiketten drucken

### ISSUE THREAD

**Issue by hitzgingerev** [braunau-mobil/velo-basar#95]
Add "Farbe", "Reifengröße" sowie "Rahmennummer" to the label

**Comment by hitzgingerev** [comment]
Bei Verkäufer-ID Nr. 3 wurden die zwei Artikel zu unterschiedlichen Zeitpunkten erfasst. Werden die Etiketten zu dem Verkäufer gedruckt, so kommt nur das Etikett des letzten erfassten Artikel

**Comment by Spacelord-XaN** [comment]
* Fehlende Infos ergänzt
* Etikettendruck auf Verkäufer Ebene gibt nun immer alle Etiketten für den Verkäufer zurück.

**Comment by hitzgingerev** [comment]
Retest 31.12.19 - fixed
