### ISSUE TITLE
Maske Verkäufer - Details anzeigen

### ISSUE THREAD

**Issue by hitzgingerev** [braunau-mobil/velo-basar#96]
Testbasar_Evelyn:

Maske Verkäufer:
Bei Verkäufer ID Nr. 6 wurde zu unterschiedlichem Zeitpunkt 2 Artikel erfasst.
Bei Kontrolle unter Ansicht Verkäufer - Verk-ID Nr. 6 - Details kommt folgende Fehlermeldung

![Fehler_Verkäufer-ID Nr 6-Details_öffnen](https://user-images.githubusercontent.com/59145234/71580947-42924580-2b03-11ea-9596-f18b1a4c4bf2.jpg)

**Comment by Spacelord-XaN** [comment]
Das kann ich leider nicht reproduzieren.
Könntest du versuchen das Problem genauer einzugrenzen?

**Comment by hitzgingerev** [comment]
Nach Retest 04.01.20 trat der Fehler nicht mehr auf
