### ISSUE TITLE
Maske: Warenkorb / Verkäufe

### ISSUE THREAD

**Issue by hitzgingerev** [braunau-mobil/velo-basar#97]
Testbasar_Evelyn

Maske Warenkorb

- Typo: "Warenkob leeren" hier fehlt ein "R" - Warenkorb
- Verkaufsbeleg Nr. 3 konnte nicht gedruckt werden - wird jedoch nun als verkauft geführt - siehe Fehlercode:

![Fehler_Warenkorb-Verkäufe](https://user-images.githubusercontent.com/59145234/71581469-ae75ad80-2b05-11ea-9e7a-4f8e4b8ce10a.jpg)

**Comment by Spacelord-XaN** [comment]
Das Problem mit dem Verkaufsbeleg konnte ich bei mir nicht reproduzieren.
Entweder es ist mittlerweile gefixt, oder ansonsten bitte genauer Beschreibgen wie ich es reproduzieren kann.

**Comment by hitzgingerev** [comment]
Retest 04.01.20 - ok
