### ISSUE TITLE
Maske - Storno

### ISSUE THREAD

**Issue by hitzgingerev** [braunau-mobil/velo-basar#98]
Testbasar_Evelyn

Maske Storno:
Verkaufsbeleg Nr. 1: einen von zwei Artikel wieder storniert - Artikel-ID Nr. 5

- Typo: "Rechnugsbeleg" -> fehtl ein N - Rechnungsbeleg
- der aktualisierte Rechnungsbeleg kann nicht gedruckt werden

![Fehler_Storno_Verkauf-Nr 1-Artikel-ID Nr  5](https://user-images.githubusercontent.com/59145234/71581639-6efb9100-2b06-11ea-942d-fdd08b3fa270.jpg)

**Comment by Spacelord-XaN** [comment]
fixed

**Comment by hitzgingerev** [comment]
Der aktualisierte Rechnungsbeleg kann nun gedruckt werden, jedoch sind alle ursprünglichen verkauften Artikel auf der Rechnung, auch der stornierte Artikel

Storno Artikel
![Stornierter_Artikel_04 1 20](https://user-images.githubusercontent.com/59145234/71767488-07ca4c00-2f0d-11ea-9ec1-adacdfb8bbb3.jpg)

Korrigierter Verkaufsbeleg
![Korrigierter_Verkaufsbeleg_Nr3](https://user-images.githubusercontent.com/59145234/71767489-10228700-2f0d-11ea-987e-d1009e6d364d.jpg)

**Comment by Spacelord-XaN** [comment]
Verkaufsbelege werden nun aktualisiert.
Ist kein Artikel mehr übrig wird die komplette Verkaufstransaktion gelöscht.
