### ISSUE TITLE
Maske Verkäufer - Abrechnen

### ISSUE THREAD

**Issue by hitzgingerev** [braunau-mobil/velo-basar#99]
Testbasar_Evelyn

Maske Verkäufer - Abrechnen
- Die Summe des abgerechneten Betrags berücksichtigt nicht die hinterlegten 10 % Provision
![Abrechnungsmaske_Verk-ID2](https://user-images.githubusercontent.com/59145234/71581990-512f2b80-2b08-11ea-8ba7-9e0b7cafa067.jpg)

- Der Abrechnungsbeleg zeigt keine Artikel, Summen, etc. - siehe Screenshot
![Abrechnungsbeleg_Verk-ID2](https://user-images.githubusercontent.com/59145234/71581912-f4cc0c00-2b07-11ea-9e16-f7db4496e2ce.jpg)

**Comment by Spacelord-XaN** [comment]
Fixed

**Comment by hitzgingerev** [comment]
retest 04.1.2020 - ok
